name: Create Release

on:
  push:
    tags:
      - 'v*'  # This matches any tag starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you have specific requirements

      - name: Build Package
        run: python setup.py sdist bdist_wheel
        
      - name: Commit and push wheel
        run: |
          git pull
          git add -f ./dist/*.whl
          git commit -m 'pushing new wheel'
          git push
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  # This gets the tag name (e.g., refs/tags/v1.0.0)
          files: |
            dist/*.tar.gz
            dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
