name: Check for Updates and Increment Version
'on':
  push:
    branches:
      - main
jobs:
  check-update:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Read current version
        id: read_version
        run: |
          echo "CURRENT_VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Run githubworkflow_pyscript.py
        env:
          LATEST_VERSION: '${{ env.CURRENT_VERSION }}'
        run: |
          python githubworkflow_pyscript.py
      - name: Update version file
        run: >
          echo "${{ steps.read_version.outputs.NEW_VERSION }}" > version.txt

          git config --local user.email "priyanka.khatick@tigeranalytics.com"

          git config --local user.name "priyankakhatick97"

          git add version.txt

          git commit -m "Increment version to ${{
          steps.read_version.outputs.NEW_VERSION }}"

          git push
