name: Create Release and Push Wheel

on:
  push:
    tags:
      - 'v*'  # This matches any tag starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for tagging

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel  # Install setuptools and wheel
          
      - name: Install setuptools and wheel
        run: |
          pip install setuptools wheel   
      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Get Base Branch
        id: get_branch
        run: |
          # Get the commit SHA of the tag
          TAG_COMMIT=${GITHUB_REF#refs/tags/}
          # Get the branch name associated with the tag
          BASE_BRANCH=$(git branch --contains $TAG_COMMIT | grep -v "HEAD" | awk '{print $1}')
          echo "Base branch: $BASE_BRANCH"
          echo "::set-output name=branch::$BASE_BRANCH"

      - name: Push Wheel to Base Branch
        run: |
          git config --local user.name "dinesh-tiger"
          git config --local user.email "dinesh.kumar2@tigeranalytics.com"
          git checkout ${{ steps.get_branch.outputs.branch }}  # Use the base branch from the previous step
          cp dist/*.whl .
          git add *.whl
          git commit -m "Add wheel file for version ${{ github.ref }}" || echo "No changes to commit"
          git push origin ${{ steps.get_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token for authentication
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  # This gets the tag name (e.g., refs/tags/v1.0.0)
          files: |
            dist/*.tar.gz
            dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

