name: Generate Wheel File and Version Control
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install setuptools and wheel
        run: |
          pip install setuptools wheel

      - name: Calculate new version
        id: version
        shell: python
        run: |
          import re
          import os
          
          with open('hello_world/__init__.py', 'r') as f:
              content = f.read()
          
          version_match = re.search(r'__version__\s*=\s*[\'\"](.*?)[\'\"]', content)
          if version_match:
              version = version_match.group(1)
              print(f"Current version from __init__.py: {__version__}")
              with open(os.environ['GITHUB_ENV'], 'a') as env_file:
                  env_file.write(f"VERSION={version}\n")
          else:
              raise ValueError("Version not found in __init__.py")

      
